### PR TITLE
Fix issue with Sensors::setTempOffset() for SCD30 #192

### PR DESCRIPTION
**Pull request by melkati**
- [x] I tested it with a SCD30 and it's working fine at my end.
- [x] restore clang format

### CODE REVIEW

**Comment by hpsaturn** [comment]
Thanks @melkati but it has many changes with other clang format, please first send a new commit with the fix to the issue only, the clang format discussion or PR could be in other ticket.

**Comment by melkati** [comment]
I hope that this time it will be in the right format.

**Comment by hpsaturn** [comment]
I think is more easy, restore the original file and only perform the change for resolve this issue. I can't approve these multiple changes. The clang-format change, I will do that after this PR.

**Comment by melkati** [comment]
Fixed in #196

**Pull request closed without merging**
