### PR TITLE
Moving sum feature

### PR DESCRIPTION
**Pull request by hpsaturn**
## Description

- [ ] Please enter a description :D
- [x] tested only on compiling time, 3 of 4 tests ok.

### CODE REVIEW

**Comment by hpsaturn** [comment]
Hi guys, I tried to organize and do the pull request that did @iw2lsi, but I don't know maybe I did some mistake. Please @iw2lsi review the PR here in the tab "files changed". And please @roberbike try to check it, because I can't help you because I haven't the hardware. I did the PR and run the tests on the root and pass 3 of 4 tests, ESP8266 fails, but you guys should be know more.

**Comment by iw2lsi** [comment]
it seems fine to me... I have some doubts regarding src/Sensors.hpp and in particular on:

lines 132:

    X(CPM, "CPM", "CPM")       \
    X(RADIATION, "uSv/h", "Radiation") \
    X(UCOUNT, "COUNT", "UCOUNT")

line 157:
    X(SCAJOE, "CAJOE", 4)   \
    X(SCOUNT, "SCOUNT", 3) 

line 169:
                         SENSOR_ENV, 
                         SENSOR_RAD  // CAJOE_GEIGER
                         }; 

lately I'll  like to change:

 cajoe_fms = new MovingSum<uint16_t, uint32_t>(GEIGER_BUFSIZE); 

to:

cajoe_fms = new MovingSum<uint8_t, uint16_t>(GEIGER_BUFSIZE);

and check the related variable everywhere...

BTW: you do not neet a sensor... you can just use a switch or a wire between pin 26 and GND/+3v3... you'll get some bounces but that's not a problem...

The changes in the https://github.com/iw2lsi/canairio_firmware/commit/dd80980cfa76850d3531b544dea2ae4174af44f1 are really few lines regarding HASS publishing.

**Comment by hpsaturn** [comment]
@iw2lsi  you can push new changes to this branch `moving_sum_feature` in your fork, and with that the PR here will update.

**Review by roberbike — COMMENTED** [review]
Tested on esp32 with tft.
uSvh only show 0000 values. It need 2 decimals almost.
Esp 8266 is not compatible with hardware timer: hw_timer_t* geiger_timer = NULL

**Comment by hpsaturn** [comment]
@roberbike when you have some time, please check this PR. If you think that it is ok, I will merge it to geiger_version branch

**Comment by iw2lsi** [comment]
ok... I'll try that... as I told you, I have a very-basic experience w/
github.

As I'm at work now, I'll do that this evening or tomorrow.

   Giampaolo


Il giorno mer 8 giu 2022 alle ore 12:11 Antonio Vanegas <
***@***.***> ha scritto:

**Pull request merged**
